### ISSUE TITLE
Create a Roadmap page

### ISSUE THREAD

**Issue by kadamwhite** [boxart/boxart-boiler#76]
There's a lot of functionality planned for BoxArt that does not exist as of this moment. We should have a public page on the documentation site explaining that roadmap, with a link to the Waffle board so that the live progress can be viewed.

Known TODO roadmap items that should be captured on this page (to be combined with the list of done items captured in #75):

BoxArt Boiler helpers:

- [ ] Clamp - Set fixed aspect ratio of element.
- [ ] Action - Make element focusable and actionable. Can make buttons or make game characters interactive.

BoxArt components:

- [ ] Drag-and-Drop - Special case Animated to drag elements around. We don't want to DnD data, we want to DnD data's representation.
- [ ] Sprite Animation
- [ ] Anchor - Make two Anchors, the second will be positioned on top of the first.
- [ ] Runloop - Pausable and controllable timeouts. Create a set of timeouts and pause and resume them together.
- [ ] Keyboard - Help map on screen Actions so that WASD can focus actions in a many dimensional menu or tiles in a grid based game or etc.
- [ ] Batch - Update elements when their data changes. Helps React diff by explicitly saying parts that did and didn't update.
- [ ] BatchFactory - Creates Multiple Batch elements from one data object.
- [ ] Index - A candidate for a data helper. Creates an index over an array, object, map, etc to help know where relevant data is. An example is a grid based game, an Index would be used to map the x,y grid to data items. "What is at postion x,y?"
- [ ] State - A candidate for a data helper. Hold a slice of immutable data and build up a the next state transactionally. The future state is mutable until it becomes the current state.
- [ ] Struct - A candidate for a data helper. Views a member of State and returns the future mutation or the current immutable data if there is no mutation for that member yet.
- [ ] ActionLite - A non-skinned Action that boiler skins.

Webpack plugins:

- [ ] Image pipeline

**Comment by kadamwhite** [comment]
@mzgoddard I'd been envisioning this and #75 as mutually-exclusive lists, but Clamp and FullViewport appear on both—can you elaborate about where they fall on the roadmap?

**Comment by mzgoddard** [comment]
They fall on the roadmap as done. I figure the roadmap might help by showing progress in addition to what is to come.

**Comment by kadamwhite** [comment]
@mzgoddard Ah, understood; I totally agree, but I've removed them from the above list because that list is meant to capture the remaining TODOs that I will need to ensure are listed on the roadmap page.

**Comment by mzgoddard** [comment]
Sounds good to me.
